---
name: GuidedArrow
main: cl4m1n3\guidedarrow\GuidedArrow
api:
- 5.0.0
version: 2.0.0
php:
- 8.1
author: cl4m1n3

permissions:
  use.guidedarrow:
    description: Allows you to use the /guidedarrow command
    default: op
...